version: "3"
services:
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
    
